"""enrich_payments_add_bank_transactions

Revision ID: 1a8a4632ad60
Revises: b6b84478dc09
Create Date: 2026-04-03 22:52:51.394983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8a4632ad60'
down_revision: Union[str, Sequence[str], None] = 'b6b84478dc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('libelle', sa.String(length=500), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reconciled_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_reconciled_payment_id'), 'bank_transactions', ['reconciled_payment_id'], unique=False)
    op.add_column('payments', sa.Column('facture_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('mode_paiement', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('reference_externe', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('date_paiement', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE payments SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('payments', 'created_at', nullable=False)
    op.create_index(op.f('ix_payments_facture_id'), 'payments', ['facture_id'], unique=False)
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    op.create_foreign_key(None, 'payments', 'factures', ['facture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_facture_id'), table_name='payments')
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'idempotency_key')
    op.drop_column('payments', 'date_paiement')
    op.drop_column('payments', 'reference_externe')
    op.drop_column('payments', 'mode_paiement')
    op.drop_column('payments', 'facture_id')
    op.drop_index(op.f('ix_bank_transactions_reconciled_payment_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
