"""add_pec_tables

Revision ID: b6b84478dc09
Revises: f5c7bcb7faf4
Create Date: 2026-04-03 22:46:55.616968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b84478dc09'
down_revision: Union[str, Sequence[str], None] = 'f5c7bcb7faf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payer_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payer_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('numero_adherent', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['payer_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payer_contracts_client_id'), 'payer_contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_payer_contracts_organization_id'), 'payer_contracts', ['organization_id'], unique=False)
    op.create_table('pec_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('montant_demande', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_accorde', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['payer_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pec_requests_case_id'), 'pec_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_pec_requests_facture_id'), 'pec_requests', ['facture_id'], unique=False)
    op.create_index(op.f('ix_pec_requests_organization_id'), 'pec_requests', ['organization_id'], unique=False)
    op.create_table('pec_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pec_request_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pec_request_id'], ['pec_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pec_status_history_pec_request_id'), 'pec_status_history', ['pec_request_id'], unique=False)
    op.create_table('relances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pec_request_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('contenu', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pec_request_id'], ['pec_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relances_pec_request_id'), 'relances', ['pec_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relances_pec_request_id'), table_name='relances')
    op.drop_table('relances')
    op.drop_index(op.f('ix_pec_status_history_pec_request_id'), table_name='pec_status_history')
    op.drop_table('pec_status_history')
    op.drop_index(op.f('ix_pec_requests_organization_id'), table_name='pec_requests')
    op.drop_index(op.f('ix_pec_requests_facture_id'), table_name='pec_requests')
    op.drop_index(op.f('ix_pec_requests_case_id'), table_name='pec_requests')
    op.drop_table('pec_requests')
    op.drop_index(op.f('ix_payer_contracts_organization_id'), table_name='payer_contracts')
    op.drop_index(op.f('ix_payer_contracts_client_id'), table_name='payer_contracts')
    op.drop_table('payer_contracts')
    op.drop_table('payer_organizations')
    # ### end Alembic commands ###
