"""add_devis_devis_lignes

Revision ID: b8abfc7f0498
Revises: e4f2e88574bc
Create Date: 2026-04-03 22:34:58.542153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8abfc7f0498'
down_revision: Union[str, Sequence[str], None] = 'e4f2e88574bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('part_secu', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('part_mutuelle', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reste_a_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_devis_case_id'), 'devis', ['case_id'], unique=False)
    op.create_table('devis_lignes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_lignes_devis_id'), 'devis_lignes', ['devis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_lignes_devis_id'), table_name='devis_lignes')
    op.drop_table('devis_lignes')
    op.drop_index(op.f('ix_devis_case_id'), table_name='devis')
    op.drop_table('devis')
    # ### end Alembic commands ###
