"""enrich_customers_table

Revision ID: 96b612180bb4
Revises: 356db0edace1
Create Date: 2026-04-03 21:57:22.414194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b612180bb4'
down_revision: Union[str, Sequence[str], None] = '356db0edace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('social_security_number', sa.String(length=15), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'social_security_number')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
