"""add_cosium_invoices_and_products

Revision ID: c81d2f00b30f
Revises: g2a3b4c5d6e7
Create Date: 2026-04-05 02:11:17.603575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81d2f00b30f'
down_revision: Union[str, Sequence[str], None] = 'g2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosium_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cosium_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('ean_code', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('family_type', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosium_products_cosium_id'), 'cosium_products', ['cosium_id'], unique=False)
    op.create_index('ix_cosium_products_tenant_cosium', 'cosium_products', ['tenant_id', 'cosium_id'], unique=True)
    op.create_index(op.f('ix_cosium_products_tenant_id'), 'cosium_products', ['tenant_id'], unique=False)
    op.create_table('cosium_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cosium_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('total_ti', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('share_social_security', sa.Float(), nullable=False),
    sa.Column('share_private_insurance', sa.Float(), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosium_invoices_cosium_id'), 'cosium_invoices', ['cosium_id'], unique=False)
    op.create_index(op.f('ix_cosium_invoices_customer_id'), 'cosium_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cosium_invoices_invoice_number'), 'cosium_invoices', ['invoice_number'], unique=False)
    op.create_index('ix_cosium_invoices_tenant_cosium', 'cosium_invoices', ['tenant_id', 'cosium_id'], unique=True)
    op.create_index('ix_cosium_invoices_tenant_date', 'cosium_invoices', ['tenant_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_cosium_invoices_tenant_id'), 'cosium_invoices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cosium_invoices_tenant_id'), table_name='cosium_invoices')
    op.drop_index('ix_cosium_invoices_tenant_date', table_name='cosium_invoices')
    op.drop_index('ix_cosium_invoices_tenant_cosium', table_name='cosium_invoices')
    op.drop_index(op.f('ix_cosium_invoices_invoice_number'), table_name='cosium_invoices')
    op.drop_index(op.f('ix_cosium_invoices_customer_id'), table_name='cosium_invoices')
    op.drop_index(op.f('ix_cosium_invoices_cosium_id'), table_name='cosium_invoices')
    op.drop_table('cosium_invoices')
    op.drop_index(op.f('ix_cosium_products_tenant_id'), table_name='cosium_products')
    op.drop_index('ix_cosium_products_tenant_cosium', table_name='cosium_products')
    op.drop_index(op.f('ix_cosium_products_cosium_id'), table_name='cosium_products')
    op.drop_table('cosium_products')
    # ### end Alembic commands ###
