"""add_indexes_for_performance

Revision ID: c8405d5ebfc0
Revises: c887379b6a6b
Create Date: 2026-04-04 12:02:38.304260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8405d5ebfc0'
down_revision: Union[str, Sequence[str], None] = 'c887379b6a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_devis_status'), 'devis', ['status'], unique=False)
    op.create_index(op.f('ix_factures_status'), 'factures', ['status'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_pec_requests_status'), 'pec_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pec_requests_status'), table_name='pec_requests')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_factures_status'), table_name='factures')
    op.drop_index(op.f('ix_devis_status'), table_name='devis')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    # ### end Alembic commands ###
