"""add_marketing_tables

Revision ID: cecbbd09bca3
Revises: fd2705a84d63
Create Date: 2026-04-03 23:12:29.647477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecbbd09bca3'
down_revision: Union[str, Sequence[str], None] = 'fd2705a84d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_segment_id'), 'campaigns', ['segment_id'], unique=False)
    op.create_table('marketing_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_consents_client_id'), 'marketing_consents', ['client_id'], unique=False)
    op.create_table('segment_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_memberships_client_id'), 'segment_memberships', ['client_id'], unique=False)
    op.create_index(op.f('ix_segment_memberships_segment_id'), 'segment_memberships', ['segment_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_campaign_id'), 'message_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_logs_client_id'), 'message_logs', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_logs_client_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_campaign_id'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_segment_memberships_segment_id'), table_name='segment_memberships')
    op.drop_index(op.f('ix_segment_memberships_client_id'), table_name='segment_memberships')
    op.drop_table('segment_memberships')
    op.drop_index(op.f('ix_marketing_consents_client_id'), table_name='marketing_consents')
    op.drop_table('marketing_consents')
    op.drop_index(op.f('ix_campaigns_segment_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('segments')
    # ### end Alembic commands ###
