"""add_factures_facture_lignes

Revision ID: f5c7bcb7faf4
Revises: b8abfc7f0498
Create Date: 2026-04-03 22:40:57.989828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c7bcb7faf4'
down_revision: Union[str, Sequence[str], None] = 'b8abfc7f0498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date_emission', sa.DateTime(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_factures_case_id'), 'factures', ['case_id'], unique=False)
    op.create_index(op.f('ix_factures_devis_id'), 'factures', ['devis_id'], unique=False)
    op.create_table('facture_lignes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facture_lignes_facture_id'), 'facture_lignes', ['facture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facture_lignes_facture_id'), table_name='facture_lignes')
    op.drop_table('facture_lignes')
    op.drop_index(op.f('ix_factures_devis_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_case_id'), table_name='factures')
    op.drop_table('factures')
    # ### end Alembic commands ###
