"""add_reminders_plans_templates

Revision ID: fd2705a84d63
Revises: 1a8a4632ad60
Create Date: 2026-04-03 22:59:16.479671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2705a84d63'
down_revision: Union[str, Sequence[str], None] = '1a8a4632ad60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payer_type', sa.String(length=30), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('channel_sequence', sa.Text(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('payer_type', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('pec_request_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('template_used', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('response_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['pec_request_id'], ['pec_requests.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['reminder_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_facture_id'), 'reminders', ['facture_id'], unique=False)
    op.create_index(op.f('ix_reminders_pec_request_id'), 'reminders', ['pec_request_id'], unique=False)
    op.create_index(op.f('ix_reminders_plan_id'), 'reminders', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_plan_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_pec_request_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_facture_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('reminder_templates')
    op.drop_table('reminder_plans')
    # ### end Alembic commands ###
